workspace = { members = ["hello-world-macro"] }
[package]
name = "chapter003001"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello-world-macro = { path = "./hello-world-macro" }
