[package]
name = "builder-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builder-code = { path = "../builder-code" }

[lib]
proc-macro = true